algoritmo "conversao_de_reais_a_dolares"

var
   c, q :inteiro
   reais,dolares :real
inicio
      escreval("Quanto vezes quer converter?")
      leia(q)
      c<-1
      enquanto ( C<=q) faca
               Escreval("Quantos reais eu tenho? ")
               leia(reais)
               dolares <- reais/2.20
               escreval("Posso ter U$", dolares:5:2)
               c<-c+ 1
      fimenquanto
fimalgoritmo
